### ISSUE TITLE
При запуске выдает ошибку

### ISSUE THREAD

**Issue by Gripers** [LightninG8/telegram-spammer#2]
Traceback (most recent call last):
  File "dbm\dumb.py", line 82, in _create
FileNotFoundError: [Errno 2] No such file or directory: 'processed_messages.db.dat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "telegram-spammer.py", line 232, in <module>
  File "telegram-spammer.py", line 25, in __init__
  File "shelve.py", line 243, in open
  File "shelve.py", line 227, in __init__
  File "dbm\__init__.py", line 95, in open
  File "dbm\dumb.py", line 316, in open
  File "dbm\dumb.py", line 70, in __init__
  File "dbm\dumb.py", line 86, in _create
PermissionError: [Errno 13] Permission denied: 'processed_messages.db.dat'

**Comment by LightninG8** [comment]
https://disk.yandex.ru/d/AJYx1VUe1nWvPw
Пофиксил. Проверяй

**Comment by Gripers** [comment]
> https://disk.yandex.ru/d/AJYx1VUe1nWvPw Пофиксил. Проверяй

ок, спасибо
